# directory for autogenerated configs
# -----------------------------------------------------------------------------
# Variables
# -----------------------------------------------------------------------------

get_filename_component(HELLOWORLD_PROJECT_DIR "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

set(PROJ_AUTOGEN_DIR ${CMAKE_BINARY_DIR}/autogen/helloworld)
file(MAKE_DIRECTORY ${PROJ_AUTOGEN_DIR})


# -----------------------------------------------------------------------------
# Generating config files
# -----------------------------------------------------------------------------

configure_file(${HELLOWORLD_PROJECT_DIR}/cmake/configs/version.h.in ${PROJ_AUTOGEN_DIR}/version.h @ONLY)